receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  otlp:
    endpoint: "api.honeycomb.io:443" # US instance
    headers:
      "x-honeycomb-team": ${env:HONEYCOMB_API_KEY}

  debug:
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]
